"""AnotherMigration

Revision ID: 209e068d607d
Revises: 8480e2511e52
Create Date: 2025-05-18 20:25:06.173111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209e068d607d'
down_revision: Union[str, None] = '8480e2511e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('reservationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reservationId')
    )
    op.create_foreign_key(None, 'stand', 'reservation', ['reservationId'], ['reservationId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stand', type_='foreignkey')
    op.drop_table('reservation')
    # ### end Alembic commands ###
